name: Release
on:
  push:
    branches:
      - main

permissions:
  contents: read 

jobs:
  release:
    name: Release
    runs-on: gha-runner-docusaurus-theme
    permissions:
      contents: write
      issues: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20.x"
          registry-url: "https://npm.pkg.github.com"
          scope: "@trosvald"

      - name: Install Production Node Dependencies
        run: corepack yarn install

      - name: Install dependencies
        run: corepack yarn
      
      - name: Build step
        run: corepack yarn run build

      - name: Release
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.GH_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.GH_TOKEN }}